apiVersion: monitoring.gaiser.bayern/v1alpha1
kind: BlackboxProbe
metadata:
  name: grpc-services
  namespace: monitoring
spec:
  exporterRef:
    name: main
  moduleRef:
    name: grpc-health
  targets:
    - grpc-api.default.svc.cluster.local:443
  interval: 30s
