apiVersion: monitoring.gaiser.bayern/v1alpha1
kind: BlackboxProbe
metadata:
  name: tls-check
  namespace: monitoring
spec:
  exporterRef:
    name: main
  moduleRef:
    name: https-tls-required
  targets:
    - https://example.com
    - https://api.example.com
  interval: 60s
  scrapeTimeout: 10s
