---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-monitoring-gaiser-bayern-v1alpha1-blackboxexporter
  failurePolicy: Fail
  name: vblackboxexporter.kb.io
  rules:
  - apiGroups:
    - monitoring.gaiser.bayern
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - blackboxexporters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-monitoring-gaiser-bayern-v1alpha1-blackboxmodule
  failurePolicy: Fail
  name: vblackboxmodule.kb.io
  rules:
  - apiGroups:
    - monitoring.gaiser.bayern
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - blackboxmodules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-monitoring-gaiser-bayern-v1alpha1-blackboxprobe
  failurePolicy: Fail
  name: vblackboxprobe.kb.io
  rules:
  - apiGroups:
    - monitoring.gaiser.bayern
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - blackboxprobes
  sideEffects: None
