apiVersion: monitoring.gaiser.bayern/v1alpha1
kind: BlackboxProbe
metadata:
  name: authenticated-endpoints
  namespace: monitoring
spec:
  exporterRef:
    name: main
  moduleRef:
    name: http-basic-auth
  targets:
    - https://admin.example.com/health
  interval: 60s
