apiVersion: monitoring.gaiser.bayern/v1alpha1
kind: BlackboxModule
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter-operator
    app.kubernetes.io/managed-by: kustomize
    exporter: blackboxexporter-sample
  name: blackboxmodule-sample
spec:
  timeout: 5s
  http:
    method: GET
    followRedirects: true
    validStatusCodes:
      - 200
