apiVersion: monitoring.gaiser.bayern/v1alpha1
kind: BlackboxProbe
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter-operator
    app.kubernetes.io/managed-by: kustomize
  name: blackboxprobe-sample
spec:
  exporterRef:
    name: blackboxexporter-sample
  moduleRef:
    name: blackboxmodule-sample
  targets:
    - https://example.com
  interval: 60s
  scrapeTimeout: 10s
