//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuth) DeepCopyInto(out *BasicAuth) {
	*out = *in
	out.PasswordRef = in.PasswordRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuth.
func (in *BasicAuth) DeepCopy() *BasicAuth {
	if in == nil {
		return nil
	}
	out := new(BasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxExporter) DeepCopyInto(out *BlackboxExporter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxExporter.
func (in *BlackboxExporter) DeepCopy() *BlackboxExporter {
	if in == nil {
		return nil
	}
	out := new(BlackboxExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlackboxExporter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxExporterCustomValidator) DeepCopyInto(out *BlackboxExporterCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxExporterCustomValidator.
func (in *BlackboxExporterCustomValidator) DeepCopy() *BlackboxExporterCustomValidator {
	if in == nil {
		return nil
	}
	out := new(BlackboxExporterCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxExporterList) DeepCopyInto(out *BlackboxExporterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlackboxExporter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxExporterList.
func (in *BlackboxExporterList) DeepCopy() *BlackboxExporterList {
	if in == nil {
		return nil
	}
	out := new(BlackboxExporterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlackboxExporterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxExporterSpec) DeepCopyInto(out *BlackboxExporterSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Image = in.Image
	in.Resources.DeepCopyInto(&out.Resources)
	if in.AdditionalArgs != nil {
		in, out := &in.AdditionalArgs, &out.AdditionalArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ServiceMonitor.DeepCopyInto(&out.ServiceMonitor)
	in.ModuleSelector.DeepCopyInto(&out.ModuleSelector)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdditionalAnnotations != nil {
		in, out := &in.AdditionalAnnotations, &out.AdditionalAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxExporterSpec.
func (in *BlackboxExporterSpec) DeepCopy() *BlackboxExporterSpec {
	if in == nil {
		return nil
	}
	out := new(BlackboxExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxExporterStatus) DeepCopyInto(out *BlackboxExporterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxExporterStatus.
func (in *BlackboxExporterStatus) DeepCopy() *BlackboxExporterStatus {
	if in == nil {
		return nil
	}
	out := new(BlackboxExporterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxModule) DeepCopyInto(out *BlackboxModule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxModule.
func (in *BlackboxModule) DeepCopy() *BlackboxModule {
	if in == nil {
		return nil
	}
	out := new(BlackboxModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlackboxModule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxModuleCustomValidator) DeepCopyInto(out *BlackboxModuleCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxModuleCustomValidator.
func (in *BlackboxModuleCustomValidator) DeepCopy() *BlackboxModuleCustomValidator {
	if in == nil {
		return nil
	}
	out := new(BlackboxModuleCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxModuleList) DeepCopyInto(out *BlackboxModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlackboxModule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxModuleList.
func (in *BlackboxModuleList) DeepCopy() *BlackboxModuleList {
	if in == nil {
		return nil
	}
	out := new(BlackboxModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlackboxModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxModuleSpec) DeepCopyInto(out *BlackboxModuleSpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPProbeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(TCPProbeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(DNSProbeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ICMP != nil {
		in, out := &in.ICMP, &out.ICMP
		*out = new(ICMPProbeConfig)
		**out = **in
	}
	if in.GRPC != nil {
		in, out := &in.GRPC, &out.GRPC
		*out = new(GRPCProbeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Unix != nil {
		in, out := &in.Unix, &out.Unix
		*out = new(UnixProbeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Websocket != nil {
		in, out := &in.Websocket, &out.Websocket
		*out = new(WebsocketProbeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxModuleSpec.
func (in *BlackboxModuleSpec) DeepCopy() *BlackboxModuleSpec {
	if in == nil {
		return nil
	}
	out := new(BlackboxModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxModuleStatus) DeepCopyInto(out *BlackboxModuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReferencedByExporters != nil {
		in, out := &in.ReferencedByExporters, &out.ReferencedByExporters
		*out = make([]NamespacedReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxModuleStatus.
func (in *BlackboxModuleStatus) DeepCopy() *BlackboxModuleStatus {
	if in == nil {
		return nil
	}
	out := new(BlackboxModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxProbe) DeepCopyInto(out *BlackboxProbe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxProbe.
func (in *BlackboxProbe) DeepCopy() *BlackboxProbe {
	if in == nil {
		return nil
	}
	out := new(BlackboxProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlackboxProbe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxProbeCustomValidator) DeepCopyInto(out *BlackboxProbeCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxProbeCustomValidator.
func (in *BlackboxProbeCustomValidator) DeepCopy() *BlackboxProbeCustomValidator {
	if in == nil {
		return nil
	}
	out := new(BlackboxProbeCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxProbeList) DeepCopyInto(out *BlackboxProbeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlackboxProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxProbeList.
func (in *BlackboxProbeList) DeepCopy() *BlackboxProbeList {
	if in == nil {
		return nil
	}
	out := new(BlackboxProbeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlackboxProbeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxProbeSpec) DeepCopyInto(out *BlackboxProbeSpec) {
	*out = *in
	out.ExporterRef = in.ExporterRef
	out.ModuleRef = in.ModuleRef
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressTargetConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MetricRelabelings != nil {
		in, out := &in.MetricRelabelings, &out.MetricRelabelings
		*out = make([]RelabelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxProbeSpec.
func (in *BlackboxProbeSpec) DeepCopy() *BlackboxProbeSpec {
	if in == nil {
		return nil
	}
	out := new(BlackboxProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxProbeStatus) DeepCopyInto(out *BlackboxProbeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProbeRef != nil {
		in, out := &in.ProbeRef, &out.ProbeRef
		*out = new(NamespacedReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxProbeStatus.
func (in *BlackboxProbeStatus) DeepCopy() *BlackboxProbeStatus {
	if in == nil {
		return nil
	}
	out := new(BlackboxProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSProbeConfig) DeepCopyInto(out *DNSProbeConfig) {
	*out = *in
	if in.RecursionDesired != nil {
		in, out := &in.RecursionDesired, &out.RecursionDesired
		*out = new(bool)
		**out = **in
	}
	if in.ValidRcodes != nil {
		in, out := &in.ValidRcodes, &out.ValidRcodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValidateAnswer != nil {
		in, out := &in.ValidateAnswer, &out.ValidateAnswer
		*out = new(DNSRRValidator)
		(*in).DeepCopyInto(*out)
	}
	if in.ValidateAuthority != nil {
		in, out := &in.ValidateAuthority, &out.ValidateAuthority
		*out = new(DNSRRValidator)
		(*in).DeepCopyInto(*out)
	}
	if in.ValidateAdditional != nil {
		in, out := &in.ValidateAdditional, &out.ValidateAdditional
		*out = new(DNSRRValidator)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSProbeConfig.
func (in *DNSProbeConfig) DeepCopy() *DNSProbeConfig {
	if in == nil {
		return nil
	}
	out := new(DNSProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRRValidator) DeepCopyInto(out *DNSRRValidator) {
	*out = *in
	if in.FailIfMatchesRegexp != nil {
		in, out := &in.FailIfMatchesRegexp, &out.FailIfMatchesRegexp
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailIfNotMatchesRegexp != nil {
		in, out := &in.FailIfNotMatchesRegexp, &out.FailIfNotMatchesRegexp
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRRValidator.
func (in *DNSRRValidator) DeepCopy() *DNSRRValidator {
	if in == nil {
		return nil
	}
	out := new(DNSRRValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GRPCProbeConfig) DeepCopyInto(out *GRPCProbeConfig) {
	*out = *in
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GRPCProbeConfig.
func (in *GRPCProbeConfig) DeepCopy() *GRPCProbeConfig {
	if in == nil {
		return nil
	}
	out := new(GRPCProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProbeConfig) DeepCopyInto(out *HTTPProbeConfig) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ValidStatusCodes != nil {
		in, out := &in.ValidStatusCodes, &out.ValidStatusCodes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ValidHTTPVersions != nil {
		in, out := &in.ValidHTTPVersions, &out.ValidHTTPVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FollowRedirects != nil {
		in, out := &in.FollowRedirects, &out.FollowRedirects
		*out = new(bool)
		**out = **in
	}
	if in.FailIfBodyMatchesRegexp != nil {
		in, out := &in.FailIfBodyMatchesRegexp, &out.FailIfBodyMatchesRegexp
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailIfBodyNotMatchesRegexp != nil {
		in, out := &in.FailIfBodyNotMatchesRegexp, &out.FailIfBodyNotMatchesRegexp
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailIfHeaderMatchesRegexp != nil {
		in, out := &in.FailIfHeaderMatchesRegexp, &out.FailIfHeaderMatchesRegexp
		*out = make([]HeaderMatchConfig, len(*in))
		copy(*out, *in)
	}
	if in.FailIfHeaderNotMatchesRegexp != nil {
		in, out := &in.FailIfHeaderNotMatchesRegexp, &out.FailIfHeaderNotMatchesRegexp
		*out = make([]HeaderMatchConfig, len(*in))
		copy(*out, *in)
	}
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuth)
		**out = **in
	}
	if in.OAuth2 != nil {
		in, out := &in.OAuth2, &out.OAuth2
		*out = new(OAuth2Config)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProbeConfig.
func (in *HTTPProbeConfig) DeepCopy() *HTTPProbeConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderMatchConfig) DeepCopyInto(out *HeaderMatchConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderMatchConfig.
func (in *HeaderMatchConfig) DeepCopy() *HeaderMatchConfig {
	if in == nil {
		return nil
	}
	out := new(HeaderMatchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMPProbeConfig) DeepCopyInto(out *ICMPProbeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMPProbeConfig.
func (in *ICMPProbeConfig) DeepCopy() *ICMPProbeConfig {
	if in == nil {
		return nil
	}
	out := new(ICMPProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTargetConfig) DeepCopyInto(out *IngressTargetConfig) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	if in.RelabelConfigs != nil {
		in, out := &in.RelabelConfigs, &out.RelabelConfigs
		*out = make([]RelabelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTargetConfig.
func (in *IngressTargetConfig) DeepCopy() *IngressTargetConfig {
	if in == nil {
		return nil
	}
	out := new(IngressTargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSelector) DeepCopyInto(out *ModuleSelector) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSelector.
func (in *ModuleSelector) DeepCopy() *ModuleSelector {
	if in == nil {
		return nil
	}
	out := new(ModuleSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSelector) DeepCopyInto(out *NamespaceSelector) {
	*out = *in
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSelector.
func (in *NamespaceSelector) DeepCopy() *NamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedReference) DeepCopyInto(out *NamespacedReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedReference.
func (in *NamespacedReference) DeepCopy() *NamespacedReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2Config) DeepCopyInto(out *OAuth2Config) {
	*out = *in
	out.ClientSecretRef = in.ClientSecretRef
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2Config.
func (in *OAuth2Config) DeepCopy() *OAuth2Config {
	if in == nil {
		return nil
	}
	out := new(OAuth2Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResponseConfig) DeepCopyInto(out *QueryResponseConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResponseConfig.
func (in *QueryResponseConfig) DeepCopy() *QueryResponseConfig {
	if in == nil {
		return nil
	}
	out := new(QueryResponseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelabelConfig) DeepCopyInto(out *RelabelConfig) {
	*out = *in
	if in.SourceLabels != nil {
		in, out := &in.SourceLabels, &out.SourceLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelabelConfig.
func (in *RelabelConfig) DeepCopy() *RelabelConfig {
	if in == nil {
		return nil
	}
	out := new(RelabelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorConfig) DeepCopyInto(out *ServiceMonitorConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorConfig.
func (in *ServiceMonitorConfig) DeepCopy() *ServiceMonitorConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPProbeConfig) DeepCopyInto(out *TCPProbeConfig) {
	*out = *in
	if in.QueryResponse != nil {
		in, out := &in.QueryResponse, &out.QueryResponse
		*out = make([]QueryResponseConfig, len(*in))
		copy(*out, *in)
	}
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPProbeConfig.
func (in *TCPProbeConfig) DeepCopy() *TCPProbeConfig {
	if in == nil {
		return nil
	}
	out := new(TCPProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CARef != nil {
		in, out := &in.CARef, &out.CARef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.CertRef != nil {
		in, out := &in.CertRef, &out.CertRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.KeyRef != nil {
		in, out := &in.KeyRef, &out.KeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnixProbeConfig) DeepCopyInto(out *UnixProbeConfig) {
	*out = *in
	if in.QueryResponse != nil {
		in, out := &in.QueryResponse, &out.QueryResponse
		*out = make([]QueryResponseConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnixProbeConfig.
func (in *UnixProbeConfig) DeepCopy() *UnixProbeConfig {
	if in == nil {
		return nil
	}
	out := new(UnixProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebsocketProbeConfig) DeepCopyInto(out *WebsocketProbeConfig) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebsocketProbeConfig.
func (in *WebsocketProbeConfig) DeepCopy() *WebsocketProbeConfig {
	if in == nil {
		return nil
	}
	out := new(WebsocketProbeConfig)
	in.DeepCopyInto(out)
	return out
}
