replicaCount: 1

image:
  repository: ghcr.io/sebastiangaiser/blackbox-exporter-operator
  tag: ""  # Defaults to appVersion
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

leaderElection:
  enabled: true

webhook:
  enabled: true
  # cert-manager is required when webhooks are enabled
  certManager:
    issuerRef:
      kind: Issuer
      name: ""  # Defaults to self-signed issuer created by the chart
